services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app/app.py
    ports:
      - "5959:5959"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./backend/.env
    networks:
      internal:
        ipv4_address: 172.20.0.2
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32g
        reservations:
          cpus: '3'
          memory: 8g
networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1